[tool.poetry]
name = "metheus-server"
version = "0.1.0"
description = ""
authors = ["nukopy <pytwbf201830@gmail.com>,"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.63.0"
fastapi-auth0 = "^0.1.6"
python-dotenv = "^0.16.0"
uvicorn = "^0.13.4"
SQLAlchemy = "^1.4.4"
mysqlclient = "^2.0.3"
boto3 = "^1.17.44"
PyJWT = "^2.0.1"
<<<<<<< HEAD
cryptography = "^3.4.7"
pycrypto = "^2.6.1"
=======
>>>>>>> dev

[tool.poetry.dev-dependencies]
ipython = "^7.22.0"
isort = "^5.8.0"
flake8 = "^3.9.0"
pytest = "^6.2.2"
black = "^20.8b1"
mypy = "^0.812"
pytest-cov = "^2.11.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
